name: API CI

on:
  push:
    paths:
      - 'apps/api/**'
      - 'apps/front/**'
      - '.github/workflows/api-ci.yml'

  pull_request:
    paths:
      - 'apps/api/**'
      - 'apps/front/**'

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://dummy:dummy@localhost:5432/dummy'
        working-directory: ./apps/api

      - name: Run unit tests
        run: npm test
        working-directory: ./apps/api

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: unit-test

    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://dummy:dummy@localhost:5432/dummy'
        working-directory: ./apps/api

      - name: Run E2E Tests
        working-directory: ./apps/api
        env:
          CI: 'true'
          DATABASE_URL: postgresql://user:password@localhost:5434/test_db?schema=public
          REDIS_HOST: localhost
          REDIS_PORT: 6380
        run: npm run test:e2e

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test

    if: >
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.base_ref == 'main')

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://dummy:dummy@localhost:5432/dummy'
        working-directory: ./apps/api

      - name: Run Integration Tests
        working-directory: ./apps/api
        env:
          CI: 'true'
          DATABASE_URL: postgresql://user:password@localhost:5434/test_db?schema=public
          REDIS_HOST: localhost
          REDIS_PORT: 6380
        run: npm run test:int

  front-test:
    name: Frontend Unit & Integration Tests
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/front/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Frontend Unit Tests
        working-directory: ./apps/front
        run: npm test

  front-e2e:
    name: Frontend e2e Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Start frontend
        working-directory: ./apps/front
        run: npm run dev &

      - name: Wait until frontend is ready
        run: |
          echo "Waiting for Frontend at http://localhost:3000..."
          for i in {1..40}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Frontend is UP!"
              exit 0
            fi
            echo "Waiting..."
            sleep 3
          done
          echo "Frontend did NOT start!"
          exit 1

      - name: Run Cypress tests
        working-directory: ./apps/front
        env:
          CYPRESS_baseUrl: http://localhost:3000
          CI: true
        run: npx cypress run
